export const mockedContact = {
  id: "1",
  firstName: "John",
  lastName: "Doe",
  username: "johndoe",
  phone: "1234567890",
  photo: {
    flags: 1,
    hasVideo: false,
    personal: false,
    photoId: "123",
    strippedThumb: {
      type: "123",
      data: [1, 2],
    },
    dcId: 2,
    className: "photo",
  },
  mutual: false,
  deleted: false,
  bot: false,
  verified: false,
  premium: false,
  fake: false,
  scam: false,
  grinderyUser: false,
  invited: false,
  status: {
    className: "offline",
  },
};
